[package]
name = "sway-rkbd-rs"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
target-cpu = "native"
codegen-units = 1
opt-level = 3
panic = "abort"

[dependencies]
i3ipc = "0.10.1"
json = "0.12.4"
single-instance = "0.3.1"
swayipc = "2.7.2"
xdg = "2.2.0"
